version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: events_rewards_db
    environment:
      POSTGRES_DB: events_rewards
      POSTGRES_USER: events_user
      POSTGRES_PASSWORD: events_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - events_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: events_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5051:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - events_network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: events_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    volumes:
      - minio_data:/data
    networks:
      - events_network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
  minio_data:

networks:
  events_network:
    driver: bridge
